
mongodata:
  image: mongo:latest
  volumes:
    - /data/db
  command: --break-mongo
mongo:
  image: mongo:latest
  volumes_from:
    - mongodata
  ports:
    - 27017:27017
  command: --port 27017 --smallfiles --rest
